### ISSUE TITLE
Why it is replacing my custom tag attribute underscore with a colon?

### ISSUE THREAD

**Issue by evandrocoan** [Knio/dominate#106]
If I render a code like:
```python
doc = dominate.tags.font( color=first_matched_color, grammar_scope=grammar_scope )

with doc:
    dominate.util.text( matched_text )
```
When it generates the html, the underscore _ on the name `grammar_scope` is replaced by a colon :
```html
<font color="#FF0000" grammar:scope="comment.start.sma">//</font>
```

**Comment by Knio** [comment]
This is an artifact of some workarounds to make some HTML names more usable in Python, since python variable names cannot contain `:`. It looks like attribute namespaces are only allowed in a few specific cases however, so I've changed this behavior to only apply then and not in general. (Fixed in 6893d1d, version 2.3.5).

You can always directly set attributes to bypass this behavior, i.e.:

```python
f = font()
f.attributes['grammar_scope'] = 'foo'
```
